GET http://localhost:3000/posts
Authorization: Bearers eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTY3NDg3MzIyMH0.hx7gnv_yzQM3gnfEcuVKZezO6Hkyz-2KIFacynqQORg

###
POST http://localhost:3000/login
Content-Type: application/json

{
"username": "John"
}